repos:
-   repo: https://github.com/python/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.8
      args: [--config=./pyproject.toml]
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.9.0
    hooks:
    - id: reorder-python-imports
      args: [--application-directories=.]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.761'
    hooks:
    - id: mypy
      args: ['--config=./setup.cfg']
