name: Test qwazzock

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Set up
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        make init
    - name: Run tests
      run: |
        make test
